
build-back:
  image: maven:3.6.2-jdk-11
  stage: build
  script:
    - cd diaballik-backend
    - mvn clean package

build-front:
  image: node:12.13
  stage: build
  script:
    - cd diaballik-frontend
    - npm install
    - npm run ng build

